In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


Tensor:Scalar

In [ ]:
scalar =torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

Random image size tensor

In [ ]:
random_img_tensor = torch.rand(size=(224,224,3))
random_img_tensor.shape,random_img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Tensor of zeros and ones

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.dtype

torch.float32

Torch ranges and tensor-like

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_to_range = torch.arange(start=10,end=250,step=5)

In [ ]:
ten_zeros = torch.zeros_like(input=ten_to_range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float16tensor = float_32_tensor.type(torch.float16)
float16tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6497, 0.0775, 0.4181, 0.5074],
        [0.2591, 0.8097, 0.6733, 0.3142],
        [0.5872, 0.4442, 0.6961, 0.4031]])

In [ ]:
transposed = some_tensor.T
print(f'previous: {some_tensor.shape}')
print(f'transposed: {transposed.shape}')

previous: torch.Size([3, 4])
transposed: torch.Size([4, 3])


In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6497, 0.0775, 0.4181, 0.5074],
        [0.2591, 0.8097, 0.6733, 0.3142],
        [0.5872, 0.4442, 0.6961, 0.4031]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


Manipulating Tensors

Tensor operations include:
1. Addition
2. Substraction
3. Division
4. Multiplication
5. Matrix multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor = tensor + 150

In [ ]:
tensor*10

tensor([1510, 1520, 1530])

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(69314)
CPU times: user 1.86 ms, sys: 0 ns, total: 1.86 ms
Wall time: 3.48 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 548 µs, sys: 964 µs, total: 1.51 ms
Wall time: 10.4 ms


tensor(69314)

Tensor Aggregation

Min Max Mean Sum

In [ ]:
x = torch.arange(5,100,10)
x

tensor([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [ ]:
torch.min(x)

tensor(5)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(50.)

In [ ]:
torch.median(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.argmin(x)

tensor(0)

Reshaping the tensor

In [ ]:
import torch
x = torch.arange(1.,16.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15.]),
 torch.Size([15]))

In [ ]:
x_reshaped = x.reshape(1,15)
x_reshaped,x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15.]]),
 torch.Size([1, 15]))

In [ ]:
x_squeez = x_reshaped.squeeze()
x_squeez,x_squeez.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15.]),
 torch.Size([15]))

In [ ]:
x_unsqueezed = x_reshaped.unsqueeze(dim=1)
x_unsqueezed,x_unsqueezed.shape

(tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
           15.]]]),
 torch.Size([1, 1, 15]))

In [ ]:
x_original = torch.rand(size=(220,224,3))
x_original.shape

torch.Size([220, 224, 3])

In [ ]:
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 220, 224])

Indexing to select the data

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][1][2]

tensor(6)

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[0,0,1]

tensor(2)

Pytorch tensors and Numpy

In [ ]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

**Reproducibility**

To reduce the randomness in NN use random seed

In [ ]:
import torch

random_tensor_A = torch.rand(3,5)
random_tensor_B = torch.rand(3,5)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9003, 0.1196, 0.4900, 0.4450, 0.6570],
        [0.6351, 0.6339, 0.9998, 0.2880, 0.9296],
        [0.7367, 0.9462, 0.5907, 0.9515, 0.8206]])
tensor([[0.0369, 0.4998, 0.1077, 0.6671, 0.4825],
        [0.7139, 0.3214, 0.4559, 0.4441, 0.0414],
        [0.8941, 0.3374, 0.5624, 0.2973, 0.5836]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [ ]:
import torch
RANDOM_SEED1 = 50
RANDOM_SEED2 = 42
torch.manual_seed(RANDOM_SEED1)
random_tensor_C = torch.rand(3,5)
torch.manual_seed(RANDOM_SEED2)
random_tensor_D = torch.rand(3,5)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.6180, 0.0687, 0.3893, 0.0404, 0.4013],
        [0.1442, 0.4605, 0.4877, 0.5927, 0.9634],
        [0.1230, 0.4048, 0.4985, 0.9987, 0.6049]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


Chapter 30: Accessing the GPU

In [ ]:
!nvidia-smi

Wed Apr  2 13:31:18 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   53C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
##Accessing GPU
import torch
torch.cuda.is_available()

True

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

**PYTORCH WORKFLOW**

1. Go through the depp learning module on Github when in doubt
2. Learnpytorch.io